apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: local
      protocol: layer2
      addresses:
      - 192.168.1.200-192.168.1.254
    - name: poke-verse
      protocol: layer2
      addresses:
      - 10.147.17.200-10.147.17.254